model:
  input_dim: 128
  node_dim: 64
  edge_input_dim: 32
  edge_dim: 32
  gnn_layers: 2

loss_weights:
  contrastive_graph: 0.0
  contrastive_node: 0.0
  contrastive_edge: 0.0
  pu: 1.0

contrastive:
  temperature: 0.5
  use_node: false
  use_edge: false

augment:
  drop_prob: 0.2
  strategy: "structure-aware"

epochs: 50